# 1. Creating Arrays using Numpy Functions

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])

In [3]:
a

array([1, 2, 3])

In [5]:
b = np.arange(0,10,2)
b

array([0, 2, 4, 6, 8])

In [7]:
c = np.zeros((2,3))
c

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
d = np.ones((3,4), dtype = int)
d

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [15]:
f = np.eye(4)
print("Identity Matrix f: \n", f)

Identity Matrix f: 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# 2. Array Manipulation Functions

In [25]:
    # Reshape an Array


a1 = np.array([1,2,3])
reshaped = np.reshape(a1, (3,1))             # this will reshape to 1 x 3
print("Reshaped Array :\n",reshaped)

Reshaped Array :
 [[1]
 [2]
 [3]]


In [26]:
    # Flatten an Array


f1 = np.array([[1,2],[3,4]])
flattened = np.ravel(f1)                      # this will flatten to 1D Array
print("Flattened Array : ",flattened)

Flattened Array :  [1 2 3 4]


In [28]:
   #  Transpose of an Array


e1 = np.array([[1,2],[3,4]])
print(np.transpose(e1))

[[1 3]
 [2 4]]


In [29]:
   # Stack Arrays Vertically


a2 = np.array([1,2,3])
b2 = np.array([4,5,6])
print("Stack Array:\n ", np.vstack([a2,b2]))


Stack Array:
  [[1 2 3]
 [4 5 6]]


In [30]:
  # Stack Arrays horizontally


a2 = np.array([1,2,3])
b2 = np.array([4,5,6])
print("Stack Array:\n ", np.hstack([a2,b2]))

Stack Array:
  [1 2 3 4 5 6]
